# Generated by Django 2.2.6 on 2021-02-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldcup',
            name='championCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='worldcup',
            name='movieId',
            field=models.IntegerField(),
        ),
    ]
